# List of prediction times
tod:
  - [6, 0]
  - [9, 30]
  - [12, 0]
  - [15, 30]
  - [22, 0]
  
# desired error for Poisson distribution (1 - sum of each approximated Poisson)
epsilon: 
  10**-7 
  
# enter desired time interval for the calculation of aspiration yet-to-arrive in minutes
yta_time_interval:
 15
 
# time window after prediction time in minutes
time_window:
 480 
 
# reference year for probability of admission in time window 
reference_year: 
 2009-10
